### PR TITLE
Change constant name from DB_SLAVE to DB_REPLICA

### LINKED ISSUE #11: MW 1.34+, use DB_REPLICA
### Setup and configuration

- SMW version: 3.1.0
- SAR version: 1.0.0-alpha
- MW version: 1.31+

### Issue

Identical to https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4093

### PR DESCRIPTION
**Pull request by kghbln**
This PR is made in reference to: #11 

This PR addresses or contains:
- Renames constant to DB_REPLICA

This PR includes:
- [ ] Tests (unit/integration)
- [ ] CI build passed

Fixes #11

### CODE REVIEW

**Comment by kghbln** [comment]
Not sure why this is still failing due to `DB_SLAVE`

**Comment by mwjames** [comment]
You can merge this but the CI failure is related to ApproveRevs
version 1.0 used in the CI environment.

**Comment by kghbln** [comment]
> You can merge this but the CI failure is related to ApproveRevs version 1.0 used in the CI environment.

Just realized this too. Even AR 1.1 will not help us since this release does not contain the fix either which was merged but not yet released as 1.2.

**Comment by krabina** [comment]
As AR 1.2 is out now, is this fixed?

**Comment by kghbln** [comment]
No this is just a mess.

**Pull request merged**
